Links screen
cdiezmoran/paycode-mobile pull request #17
Opened 2022-02-04 17:09 UTC by maxruizg

2022-02-07 20:57 UTC, cdiezmoran requested changes

2022-02-07 20:57 UTC, cdiezmoran commented on src/helpers/apiParser.ts
> +  console.log(dataLinks.data);
Hay que quitar este console.log

2022-02-07 20:57 UTC, cdiezmoran commented on src/helpers/apiParser.ts
> +  // @ts-ignore
Que error de ts te da aqui? Se puede arreglar?

2022-02-07 20:57 UTC, cdiezmoran commented on src/hooks/useAuthorization.ts
> +    SecureStore.deleteItemAsync('PAYCODE_USR_TOKEN');
Hay que quitar esto que forza el logout

2022-02-07 20:57 UTC, cdiezmoran commented on src/screens/LinksScreen.tsx
> +    page: 1
Aqui no es necesario que mandes page: 1 porque tus defaultArgs tienen page: 1 como default

2022-02-07 20:57 UTC, cdiezmoran commented on src/screens/LinksScreen.tsx
> +        'DD MMM YYYY, HH:MM A'
Aquí usas el mismo formato para la fecha pago y para la fecha limite, lo podrías extraer a una variable y usarla en los dos lugares

2022-02-07 20:57 UTC, cdiezmoran commented on src/screens/LinksScreen.tsx
> +  const keyExtractor = (item: Link, index: number) => `link-row-${index}`;
Aquí puedes usar el codeLink como ID ya que es único y es mejor que usar index la función quedaría asi: `const keyExtractor = (item: Link) => item.codeLink;`

2022-02-07 20:57 UTC, cdiezmoran commented on src/screens/LinksScreen.tsx
> +  console.log(links);
Hay que quitar este console.log

2022-02-07 20:57 UTC, cdiezmoran commented on src/hooks/useLinks.ts
> +        `paycode/links_pago/obtener_links_pagos?page=${page}&pageSize=10`
Cómo modificas la variable de page? Por lo que veo nunca la estas modificando entonces siempre va a cargar la misma página de links. En lugar de usar un argument para el hook podrías usar la variable que pusiste en tu slice `pages` nada mas hay que cambiarla a `page` que empiece en 1 e incrementarla cada vez que se haga la llamada a fetchLinks

2022-02-07 20:57 UTC, cdiezmoran commented on src/slices/links.ts
> +  pages: 0
Esta variable representa en que página esta debería de ser `page` singular y empezar en 1 y como puse en el comment de arriba ahorita no se esta usando pero la deberías de usar para pagination

2022-02-15 18:14 UTC, maxruizg commented on src/helpers/apiParser.ts
> +  // @ts-ignore
ya lo quite y ya no me da error no me acuerdo por que lo puse

2022-02-15 18:19 UTC, maxruizg commented on src/screens/LinksScreen.tsx
> +  const keyExtractor = (item: Link, index: number) => `link-row-${index}`;
me sale un warning de que los children tienen el mismo key si lo dejo así
<img width="516" alt="Screen Shot 2022-02-15 at 12 19 02" src="https://user-images.githubusercontent.com/89366481/154124246-837945cf-5770-468c-bf02-27da2c1a6771.png">
g

2022-02-15 18:28 UTC, maxruizg commented on src/hooks/useLinks.ts
> +        `paycode/links_pago/obtener_links_pagos?page=${page}&pageSize=10`
algo así?
<img width="1147" alt="Screen Shot 2022-02-15 at 12 28 19" src="https://user-images.githubusercontent.com/89366481/154125738-c72efaaf-5eaa-4761-81f8-874a01e67638.png">
?

2022-02-25 23:38 UTC, cdiezmoran requested changes

2022-02-25 23:38 UTC, cdiezmoran commented on src/hooks/useLinks.ts
> +
Aqui para arreglar los ts-ignore de abajo tendrias que ponerle:
`const parsedData = APIParser.parse(data, 'links') as Link[];`

2022-02-25 23:38 UTC, cdiezmoran commented on src/hooks/useLinks.ts
> +      parsedData.forEach((link: any) => {
este argumento es de tipo `Link`

2022-02-25 23:38 UTC, cdiezmoran commented on src/hooks/useLinks.ts
> +  return [links, { fetchLinks }, { recentLinks }];
Aqui no regreses otro objeto como tercer argumento, para agregar mas cosas que regresar esta el segundo objecto, tendría que ser así:
`return [links, { fetchLinks, recentLinks }];`

2022-02-25 23:38 UTC, cdiezmoran commented on src/hooks/useLinks.ts
> +type ReturnType = [Link[], { fetchLinks(): void }, { recentLinks(): void }];
Hay que adaptar este ReturnType con el comment que te puse en el return de useLinks y como recentLinks y fetchLinks son async el return type tiene que estar wrappeado en promise para que no te de el error de que el await no hace nada. Quedaría asi:
`type ReturnType = [Link[], { fetchLinks(): Promise<void>, recentLinks(): Promise<void>  }];`

2022-02-26 00:16 UTC, merged